// data.js

const TRACKS_DATA = [
  // credit property added. Assumed "Crazalu" for all existing images.
  { image: "images/img1.webp",  mapX: 1479, mapY: 105, credit: "Crazalu" },
  { image: "images/img2.webp",  mapX: 1548, mapY: 653, credit: "SudaiDelphi" },
  { image: "images/img3.webp",  mapX: 103, mapY: 704, credit: "Crazalu" },
  { image: "images/img4.webp",  mapX: 156,  mapY: 626, credit: "Crazalu" },
  { image: "images/img5.webp",  mapX: 332, mapY: 220, credit: "Crazalu" },
  { image: "images/img6.webp",  mapX: 257, mapY: 248, credit: "Crazalu" },
  { image: "images/img7.webp",  mapX: 1017,  mapY: 500, credit: "Crazalu" },
  { image: "images/img8.webp",  mapX: 929,  mapY: 494, credit: "Crazalu" },
  { image: "images/img9.webp",  mapX: 970, mapY: 361, credit: "Crazalu" },
  { image: "images/img10.webp", mapX: 970, mapY: 333, credit: "Crazalu" },
  { image: "images/img11.webp", mapX: 1885,  mapY: 383, credit: "Crazalu" },
  { image: "images/img12.webp", mapX: 1807, mapY: 459, credit: "Crazalu" },
  { image: "images/img13.webp", mapX: 1717, mapY: 426, credit: "Crazalu" },
  { image: "images/img14.webp", mapX: 1690,  mapY: 312, credit: "Crazalu" },
  { image: "images/img15.webp", mapX: 1299, mapY: 957, credit: "Crazalu" },
  { image: "images/img16.webp", mapX: 1312,  mapY: 574, credit: "Crazalu" },
  { image: "images/img17.webp", mapX: 1165, mapY: 667, credit: "Crazalu" },
  { image: "images/img18.webp", mapX: 1796, mapY: 841, credit: "Crazalu" },
  { image: "images/img19.webp", mapX: 1516, mapY: 497, credit: "Crazalu" },
  { image: "images/img20.webp", mapX: 1570,  mapY: 531, credit: "Crazalu" },
  { image: "images/img21.webp", mapX: 1624, mapY: 772, credit: "LapisSR_" },
  { image: "images/img22.webp", mapX: 221,  mapY: 922, credit: "olpoker" },
  { image: "images/img23.webp", mapX: 1697, mapY: 574, credit: "Electric_Hoodie" },
  { image: "images/img24.webp", mapX: 500,  mapY: 1450, enabled: false, credit: "Crazalu" },
  { image: "images/img25.webp", mapX: 1700, mapY: 1050, enabled: false, credit: "Crazalu" },
  { image: "images/img26.webp", mapX: 1750, mapY: 600,  enabled: false, credit: "Crazalu" },
  { image: "images/img27.webp", mapX: 1600, mapY: 500,  enabled: false, credit: "Crazalu" },
  { image: "images/img28.webp", mapX: 1150, mapY: 1350, enabled: false, credit: "Crazalu" },
  { image: "images/img29.webp", mapX: 900,  mapY: 1500, enabled: false, credit: "Crazalu" },
  { image: "images/img30.webp", mapX: 1000, mapY: 300,  enabled: false, credit: "Crazalu" }
];