// data.js

const TRACKS_DATA = [
  { image: "images/img1.webp",  name: "Aurora Borealis",  mapX: 1479, mapY: 105, credit: "Crazalu" },
  { image: "images/img2.webp",  name: "Hello from Above",  mapX: 1548, mapY: 653, credit: "SudaiDelphi" },
  { image: "images/img3.webp",  name: "Torchlight",  mapX: 103,  mapY: 704, credit: "Crazalu" },
  { image: "images/img4.webp",  name: "Hello Foodtruck!",  mapX: 156,  mapY: 626, credit: "Crazalu" },
  { image: "images/img5.webp",  name: "Run! It's Burning!",  mapX: 332,  mapY: 220, credit: "Crazalu" },
  { image: "images/img6.webp",  name: "Brace for Impact.",  mapX: 257,  mapY: 248, credit: "Crazalu" },
  { image: "images/img7.webp",  name: "Can they see me?",  mapX: 1017, mapY: 500, credit: "Crazalu" },
  { image: "images/img8.webp",  name: "Beautiful Flwrfield",  mapX: 929,  mapY: 494, credit: "Crazalu" },
  { image: "images/img9.webp",  name: "Brace for Impact. 2",  mapX: 970,  mapY: 361, credit: "Crazalu" },
  { image: "images/img10.webp", name: "Cannons and Tricks", mapX: 970,  mapY: 333, credit: "Crazalu" },
  { image: "images/img11.webp", name: "Brrr!", mapX: 1885, mapY: 383, credit: "Crazalu" },
  { image: "images/img12.webp", name: "Frozen Over", mapX: 1807, mapY: 459, credit: "Crazalu" },
  { image: "images/img13.webp", name: "Toadettes Ice Cream", mapX: 1717, mapY: 426, credit: "Crazalu" },
  { image: "images/img14.webp", name: "Help! I'm falling!", mapX: 1690, mapY: 312, credit: "Crazalu" },
  { image: "images/img15.webp", name: "You got insurance?", mapX: 1299, mapY: 957, credit: "Crazalu" },
  { image: "images/img16.webp", name: "P-utiful Image!", mapX: 1312, mapY: 574, credit: "Crazalu" },
  { image: "images/img17.webp", name: "Nice Shot!", mapX: 1165, mapY: 667, credit: "Crazalu" },
  { image: "images/img18.webp", name: "Water Broadcast", mapX: 1796, mapY: 841, credit: "Crazalu" },
  { image: "images/img19.webp", name: "Heating Up", mapX: 1516, mapY: 497, credit: "Crazalu" },
  { image: "images/img20.webp", name: "Wait in Line!", mapX: 1570, mapY: 531, credit: "SudaiDelphi" },
  { image: "images/img21.webp", name: "I feel a breeze...", mapX: 1624, mapY: 772, credit: "LapisSR_" },
  { image: "images/img22.webp", name: "Thorns IV", mapX: 221,  mapY: 922, credit: "olpoker" },
  { image: "images/img23.webp", name: "Dangerous Waves", mapX: 1697, mapY: 574, credit: "Electric_Hoodie" },
  { image: "images/img24.webp", name: "Get out my boots", mapX: 109,  mapY: 782, credit: "SudaiDelphi" },
  { image: "images/img25.webp", name: "Wndr o' the Wrld?", mapX: 102,  mapY: 813, credit: "SudaiDelphi" },
  { image: "images/img26.webp", name: "Classic Standoff", mapX: 34,   mapY: 817, credit: "SudaiDelphi" },
  { image: "images/img27.webp", name: "Glidin' 2 Sandy Shores", mapX: 34,   mapY: 738, credit: "SudaiDelphi" },
  { image: "images/img28.webp", name: "Going On A Hike", mapX: 486,  mapY: 915, credit: "SudaiDelphi" },
  { image: "images/img29.webp", name: "Apocalypse", mapX: 349,  mapY: 364, credit: "SudaiDelphi" },
  { image: "images/img30.webp", name: "Beware: Danger!", mapX: 435,  mapY: 837, credit: "SudaiDelphi" },
  { image: "images/img31.webp", name: "Uh oh...", mapX: 243, mapY: 428, credit: "SudaiDelphi" },
  { image: "images/img32.webp", name: "Heeeeeelp!", mapX: 99, mapY: 649, credit: "SudaiDelphi" },
  { image: "images/img33.webp", name: "I blend in, right?", mapX: 798, mapY: 818, credit: "SudaiDelphi" },
  { image: "images/img34.webp", name: "Test Subject: Sudai", mapX: 746, mapY: 322, credit: "SudaiDelphi" },
  { image: "images/img35.webp", name: "Sewer Pipes?", mapX: 288, mapY: 871, credit: "SudaiDelphi" },
  { image: "images/img36.webp", name: "They're chasing me!", mapX: 304, mapY: 386, credit: "SudaiDelphi" },
  { image: "images/img37.webp", name: "Electrifying Waters", mapX: 874, mapY: 717, credit: "SudaiDelphi" },
  { image: "images/img38.webp", name: "Bouta Lose Reception", mapX: 388, mapY: 544, credit: "SudaiDelphi" },
  { image: "images/img39.webp", name: "Thinkin' 'bout life.", mapX: 358, mapY: 480, credit: "SudaiDelphi" },
  { image: "images/img40.webp", name: "Too Fast! Too Fast!", mapX: 909, mapY: 219, credit: "SudaiDelphi" },
  { image: "images/img41.webp", name: "Tin Tunnel Man", mapX: 425, mapY: 363, credit: "SudaiDelphi" },
  { image: "images/img42.webp", name: "Look at those plebs...", mapX: 323, mapY: 413, credit: "SudaiDelphi" },
  { image: "images/img43.webp", name: "Look at me, mom!", mapX: 359, mapY: 538, credit: "SudaiDelphi" },
  { image: "images/img44.webp", name: "Swimming, Swimming", mapX: 1021, mapY: 666, credit: "SudaiDelphi" },
  { image: "images/img45.webp", name: "RIP to Sweats", mapX: 805, mapY: 131, credit: "SudaiDelphi" },
  { image: "images/img46.webp", name: "Tropical Rainforest", mapX: 1038, mapY: 160, credit: "SudaiDelphi" },
  { image: "images/img47.webp", name: "Greenery Scenery", mapX: 958, mapY: 161, credit: "SudaiDelphi" },
  { image: "images/img48.webp", name: "Going to a Track!", mapX: 934, mapY: 169, credit: "SudaiDelphi" },
  { image: "images/img49.webp", name: "Hell Caving Over", mapX: 396, mapY: 360, credit: "SudaiDelphi" },
  { image: "images/img50.webp", name: "Hot Tub Stream", mapX: 683, mapY: 137, credit: "SudaiDelphi" },
  { image: "images/img51.webp", name: "Hot Lava Stream", mapX: 738, mapY: 124, credit: "SudaiDelphi" },
  { image: "images/img52.webp", name: "Beware of Train", mapX: 881, mapY: 582, credit: "SudaiDelphi" },
  { image: "images/img53.webp", name: "The Sahara Desert?", mapX: 200, mapY: 514, credit: "SudaiDelphi" },
  { image: "images/img54.webp", name: "Don't sting me!", mapX: 852, mapY: 416, credit: "SudaiDelphi" },
  { image: "images/img55.webp", name: "Near the Bridge", mapX: 870, mapY: 332, credit: "SudaiDelphi" },
  { image: "images/img56.webp", name: "Near-Track Metal", mapX: 853, mapY: 503, credit: "SudaiDelphi" },
  { image: "images/img57.webp", name: "A Lake of Goodies", mapX: 930, mapY: 142, credit: "SudaiDelphi" },
  { image: "images/img58.webp", name: "How do I get down?", mapX: 621, mapY: 1035, credit: "Crazalu" },
  { image: "images/img59.webp", name: "The Fountain of Youth", mapX: 1859, mapY: 773, credit: "Crazalu" },
  { image: "images/img60.webp", name: "Does she know, chat?", mapX: 1288, mapY: 127, credit: "Crazalu" }
];